maximum:
  length_email: 255
  length_name: 50
  length_content: 140
minimum:
  length_pass: 6
size:
  avar_size: 80
page:
  per_page: 5
expired_time: <%= 2.hours.ago %>
maximum_megabytes: <%= 5.megabytes %>
